import Head from "next/head";
// import Scheduler from "../scheduler/index"
import dynamic from "next/dynamic";
// import Basic from "../example/Basic"

const NewScheduler = dynamic(import("../components/newScheduler"), {
  ssr: false,
}); // Async API cannot be server-side rendered
export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NewScheduler/>
    </>
  );
}
